## Module 1: Introduction

This module consists of NumPy library introduction, linear algebra refreshments and Pandas introduction.

### Part 1: Numpy

NumPy is the fundamental package for scientific computing with Python.

Website: https://numpy.org
Documentation: https://numpy.org/doc

It provides:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

In [2]:
# import numpy to use 
import numpy as np

# create arrays
print("Array of zeros:", np.zeros(10))
print("Array of ones:", np.ones(10))
print("Array of arbitrary number:", np.full(10, 2.5))

a = np.array([1, 2, 3, 4, 5])
print("Python list as np array:", a)
print("Element of the array:", a[2])
a[2] = 10
print("Array with changed element:", a)

print("Array with a range:", np.arange(3, 10))
print("Array with linspace:", np.linspace(0, 100, 11))

Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of arbitrary number: [2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
Python list as np array: [1 2 3 4 5]
Element of the array: 3
Array with changed element: [ 1  2 10  4  5]
Array with a range: [3 4 5 6 7 8 9]
Array with linspace: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

In [3]:
# create multi-dimensional arrays
print("Multi-dim zeros:\n", np.zeros((2, 5)))

n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMulti-dim array:\n", n)
print("\nElement of the multi-dim array:", n[0, 1])
n[0, 1] = 20
print("Multi-dim array with changed element:\n", n)

print("\nRow of the multi-dim array:", n[1])
n[1] = [1, 1, 1]
print("Multi-dim array with changed row:\n", n)

print("\nColumn of the multi-dim array:", n[:, 1])
n[:, 1] = [2, 2, 2]
print("Multi-dim array with changed column:\n", n)

Multi-dim zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Multi-dim array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element of the multi-dim array: 2
Multi-dim array with changed element:
 [[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]

Row of the multi-dim array: [4 5 6]
Multi-dim array with changed row:
 [[ 1 20  3]
 [ 1  1  1]
 [ 7  8  9]]

Column of the multi-dim array: [20  1  8]
Multi-dim array with changed column:
 [[1 2 3]
 [1 2 1]
 [7 2 9]]

In [4]:
# create randomly generated arrays
np.random.seed(2) # added for reproducibility
print("2D uniform dist random array:\n", np.random.rand(5, 2))

print("\n2D normal dist random array:\n", np.random.randn(5, 2))

print("\n2D integer random array with limits:\n", np.random.randint(low=0, high=100, size=(5, 2)))

2D uniform dist random array:
 [[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]

2D normal dist random array:
 [[ 0.55145404  2.29220801]
 [ 0.04153939 -1.11792545]
 [ 0.53905832 -0.5961597 ]
 [-0.0191305   1.17500122]
 [-0.74787095  0.00902525]]

2D integer random array with limits:
 [[83 31]
 [66 80]
 [52 76]
 [50  4]
 [90 63]]

In [5]:
# element-wise operations
a = np.arange(5)
print("Array a:", a)
print("Array with elements +1:", a+1)
print("Array with elements *1:", a*2)
print("Array with elements /100:", a/100)
print("Array with elements **2:", a**2)

b = (10 + (a * 2)) **2 / 100
print("Array b:", b)

print("Array a + b:", a + b)
print("Array a / b:", a / b)

Array a: [0 1 2 3 4]
Array with elements +1: [1 2 3 4 5]
Array with elements *1: [0 2 4 6 8]
Array with elements /100: [0.   0.01 0.02 0.03 0.04]
Array with elements **2: [ 0  1  4  9 16]
Array b: [1.   1.44 1.96 2.56 3.24]
Array a + b: [1.   2.44 3.96 5.56 7.24]
Array a / b: [0.         0.69444444 1.02040816 1.171875   1.2345679 ]

In [8]:
# comparison operations
print("Array a:", a)
print("Array b:", b)

print("Array a >= 2:", a >= 2)
print("Array a > b:", a > b)

print("Array a[a > b]:", a[a > b])

Array a: [0 1 2 3 4]
Array b: [1.   1.44 1.96 2.56 3.24]
Array a >= 2: [False False  True  True  True]
Array a > b: [False False  True  True  True]
Array a[a > b]: [2 3 4]

In [10]:
# summarizing operations
print("Array a:", a)

print("Min of a:", a.min())
print("Max of a:", a.max())
print("Mean of a:", a.mean())
print("Std. dev. of a:", a.std())
print("Sum of a:", a.sum())

Array a: [0 1 2 3 4]
Min of a: 0
Max of a: 4
Mean of a: 2.0
Std. dev. of a: 1.4142135623730951
Sum of a: 10

### Part 2: Linear Algebra Refresher

In [14]:
# vector vector multipication (dot product)
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

print("Array u:", u)
print("Array v:", v)
print("Version 1: u · v:", np.dot(u, v))
print("Version 2: u · v:", u.dot(v))
print("Version 3: u @ v:", u @ v)

Array u: [2 4 5 6]
Array v: [1 0 0 2]
Version 1: u · v: 14
Version 2: u · v: 14
Version 3: u @ v: 14

In [16]:
# custom vector vector multiplication
def vec_vec_mult(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

print("Array u:", u)
print("Array v:", v)
print("Custom: u · v:", vec_vec_mult(u, v))

Array u: [2 4 5 6]
Array v: [1 0 0 2]
Custom: u · v: 14.0

In [29]:
# custom matrix vector multiplication
def mat_vec_mult(U, v):
    rows, cols = U.shape
    assert cols == v.shape[0]
    result = np.zeros(rows)

    for i in range(rows):
        result[i] = vec_vec_mult(U[i], v)

    return result

U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
print("Matrix U:\n", U)
print("Array v:", v)
print("Built-in U · v:", U.dot(v))
print("Custom U · v:", mat_vec_mult(U, v))

Matrix U:
 [[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]
Array v: [1 0 0 2]
Built-in U · v: [14  5  5]
Custom U · v: [14.  5.  5.]

In [30]:
# custom matrix matrix multiplication
def mat_mat_mult(U, V):
    rows = U.shape[0]
    cols = V.shape[1]
    assert U.shape[1] == V.shape[0]
    result = np.zeros((rows, cols))

    for i in range(cols):
        vi = V[:, i]
        Uvi = mat_vec_mult(U, vi)
        result[:, i] = Uvi

    return result

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
print("Matrix U:\n", U)
print("Matrix V:\n", U)
print("Built-in U · V:\n", U.dot(V))
print("Custom U · V:\n", mat_mat_mult(U, V))

Matrix U:
 [[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]
Matrix V:
 [[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]
Built-in U · V:
 [[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]
Custom U · V:
 [[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]

In [38]:
# identity matrix
I = np.eye(3)
print("Identity matrix I:\n", I)
print("Matrix V:\n", V)
print("I shape:", I.shape)
print("V shape:", V.shape)
print("V · I:\n", V.dot(I))

Identity matrix I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrix V:
 [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]
I shape: (3, 3)
V shape: (4, 3)
V · I:
 [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]

In [39]:
# inverse matrix
Vs = V[[0, 1, 2]]
print("Matrix Vs:\n", Vs)
print("Vs shape:", Vs.shape)

Vs_inv = np.linalg.inv(Vs)
print("Matrix Vs_inv:\n", Vs_inv)
print("Vs_inv shape:", Vs_inv.shape)

print("Matrix Vs_inv · Vs:\n", Vs_inv.dot(Vs))

Matrix Vs:
 [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]
Vs shape: (3, 3)
Matrix Vs_inv:
 [[ 1.         -2.          0.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          1.33333333 -0.33333333]]
Vs_inv shape: (3, 3)
Matrix Vs_inv · Vs:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Part 3: Pandas

It is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

#### DataFrame:

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd

# create a data frame using list of lists
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [50]:
# create a data frame using list of dictionaries
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [51]:
# show only head rows
df.head(2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

#### Series:

In [52]:
# get a column of the df
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [53]:
# get multiple columns of df
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [54]:
# add a new column to df
df['ID'] = [10, 20, 30, 40, 50]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,ID
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [55]:
# delete a column from df
del df['ID']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Index and Accessing Elements:

In [56]:
# get indices of df
df.index

RangeIndex(start=0, stop=5, step=1)

In [57]:
# get indices of series with 'Make' data 
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [61]:
# change indices naming
df.index = ['a', 'b', 'c', 'd', 'e']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [62]:
# access rows with positional index
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [63]:
# access rows with index
df.loc[['b', 'c', 'e']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [64]:
# reset indices
df = df.reset_index(drop=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Element-wise Operations:

In [ ]:
# perform operations on data
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [ ]:
# apply comparison operations on data
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

#### Filtering:

In [ ]:
# filter a specific model
df[df['Make'] == 'Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [ ]:
# filtering with multiple conditions
df[(df['Make'] == 'Nissan') & (df['Year'] >= 2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### String Operations:

In [69]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [ ]:
# lowercae string data
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [ ]:
# multiple string operations on data
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

#### Summarizing Operations:

In [ ]:
# summarize info of numeric datya rounded to 2 decimals
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [ ]:
# series with number of distinct elements
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

#### Missing Values:

In [74]:
# list missing value count in all series
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

#### Grouping:

```sql
SELECT 
    transmission_type,
    AVG(MSRP)
FROM
    cars
GROUP BY
    transmission_type
```

In [75]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

#### Getting the NumPy Arrays:

In [76]:
# get data in series as numpy array
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [77]:
# get data as a dictionary
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]